server:
  port: 8081
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #mybatis扫描别名包，与注解@alias联用
  type-aliases-package: com.jxxy.mlxc.news.api
spring:
  application:
    name: news-service
  datasource:
    druid:
      url: jdbc:mysql://129.204.56.246:3306/mlxc?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
      username: root
      password: wbdheike
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false
  dubbo:
    server: true
    registry:
      address: zookeeper://127.0.0.1:2181
      #address: zookeeper://129.204.56.246:2081?backup=129.204.56.246:2082,129.204.56.246:2083
    protocol:
      name: dubbo
      port: 20883
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 20
        max_idle: 10
        max-wait: 10
    port: 6379
    host: 129.204.56.246
    password: zym123456
    timeout: 1000
  cache:
    type: REDIS
    cache-names: redisCache
mlxc:
  #开启活动开始前短信提醒功能
  isSendActiveMsgEnable: true
  #设置活动前多久提醒
  beforeHour: 24

