server:
  port: 8083
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #mybatis扫描别名包，与注解@alias联用
  type-aliases-package: com.jxxy.mlxc.business.api.dto
spring:
  datasource:
    druid:
      url: jdbc:mysql://129.204.56.246:3306/mlxc?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
      username: root
      password: wbdheike
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false
  application:
    name: bussiness-server
  dubbo:
    server: true
    registry:
      #address: zookeeper://127.0.0.1:2181
      address: zookeeper://172.16.0.8:2181?backup=172.16.0.8:2182,172.16.0.8:2183
    protocol:
      name: dubbo
      port: 20880
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 20
        max_idle: 10
        max-wait: 10
    port: 6379
    host: 129.204.56.246
    password: zym123456
    timeout: 1000
  cache:
    type: REDIS
    cache-names: redisCache
mlxc:
  #不进行用户下单前检查
  isVerifyUser: false
  isSeckill: true
